// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADkes8dg0QMJGauF9amn3m-yp63RZhsQs',
    appId: '1:529954913948:web:130599522804f776f3b759',
    messagingSenderId: '529954913948',
    projectId: 'fenix-frontend',
    authDomain: 'fenix-frontend.firebaseapp.com',
    storageBucket: 'fenix-frontend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAhY_lQi2r1j9AhQXctA7PVV7ERS2xUg',
    appId: '1:529954913948:android:81a79538995c3db3f3b759',
    messagingSenderId: '529954913948',
    projectId: 'fenix-frontend',
    storageBucket: 'fenix-frontend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-HU6x6AWeKSVTNqy-5cYb6oyEZPt5AJI',
    appId: '1:529954913948:ios:0489ba0e718f0407f3b759',
    messagingSenderId: '529954913948',
    projectId: 'fenix-frontend',
    storageBucket: 'fenix-frontend.appspot.com',
    iosClientId: '529954913948-6v0g3o23cgeare8c9b5h5vspk2dqjttf.apps.googleusercontent.com',
    iosBundleId: 'cl.falabella.fenixsellerapp',
  );
}
